version: 2.0

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/zhoumingjun.github.io
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:b4:72:71:55:39:5f:07:7d:1d:8b:a2:93:8d:ef:36"
      - checkout
      - run:
          name: Get current site
          working_directory: ~/
          command: git clone -b master git@github.com:zhoumingjun/zhoumingjun.github.io.git public
      - run:
          name: Generate site
          working_directory: ~/zhoumingjun.github.io
          command: ls -alh && HUGO_ENV=production hugo -d ~/public
      - deploy:
          name: Deploy to Github Pages
          working_directory: ~/public
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "zhoumingjun@gmail.com"
            git config user.name "Deployment Bot"
            git add .
            git commit --allow-empty -m "Trigger deployment"
            git push -q git@github.com:zhoumingjun/zhoumingjun.github.io.git master

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: source
